# Generated by Django 6.0.4 on 2026-04-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_message_notice_notification_alter_exam_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
